### ISSUE TITLE
Return of MLSumcheck::prove

### ISSUE THREAD

**Issue by drobissout** [arkworks-rs/sumcheck#64]
Hello,

I am using the MLSumcheck implementation to prove the result of a multiplication of two polynomials but I need to get access to the state of their MLEs at the end of the prover rounds for further computations. However the MLSumcheck::prove function only returns the value of the messages sent by the prover.

```
pub fn prove(polynomial: &ListOfProductsOfPolynomials<F>) -> Result<Proof<F>, Error> {
    let mut fs_rng = Blake2s512Rng::setup();
    fs_rng.feed(&polynomial.info())?;

    let mut prover_state = IPForMLSumcheck::prover_init(&polynomial);
    let mut verifier_msg = None;
    let mut prover_msgs = Vec::with_capacity(polynomial.num_variables);
    for _ in 0..polynomial.num_variables {
        let (prover_msg, prover_state_new) = IPForMLSumcheck::prove_round(prover_state, &verifier_msg);
        prover_state = prover_state_new;
        fs_rng.feed(&prover_msg)?;
        prover_msgs.push(prover_msg);
        verifier_msg = Some(IPForMLSumcheck::sample_round(&mut fs_rng));
    }

    Ok(prover_msgs)
}
```

I was wondering if it was somehow possible to access the final value of prover_state after the function call without rewriting the function?

Thank you for your time!

**Comment by Pratyush** [comment]
I think it would be fine to modify the `prove` method to return the `prover_state` at the end (along with the `prover_msgs`). Please feel free to submit a PR for the same!
