### ISSUE TITLE
unit tests for input-output behaviour 

### ISSUE THREAD

**Issue by maciejskorski** [arkworks-rs/sumcheck#70]
I am not a rust developer and may be missing something, but does this repo contain unit tests to prove implementation correctness?

**Comment by maciejskorski** [comment]
Thanks, you are right! My two cents: many people (me included) expect the layout that places unit tests under their own dir, not inside src, this looks like:

```
adder
├── Cargo.lock
├── Cargo.toml
├── src
│   └── lib.rs
└── tests
    └── integration_test.rs
```

https://doc.rust-lang.org/book/ch11-03-test-organization.html

**Comment by Pratyush** [comment]
Unit tests in Rust tend to live alongside code; integration tests live inside the `test` folder. See the ["Unit tests"](https://doc.rust-lang.org/book/ch11-03-test-organization.html#unit-tests) heading in the document that you linked.

**Comment by maciejskorski** [comment]
Ah! Ok, thanks guys, I wasn't aware of those practices (coming with background in Python).
